// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRpiex6ULSuDQuLsLgeTm7xozFvrPJOw',
    appId: '1:346596979467:web:c1e160bd823af463b6e80e',
    messagingSenderId: '346596979467',
    projectId: 'pseicrud',
    authDomain: 'pseicrud.firebaseapp.com',
    storageBucket: 'pseicrud.firebasestorage.app',
    measurementId: 'G-VVWHV7WS3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs5ulg9--_C5lkX5wxE0GpT5Qa6AEuTcc',
    appId: '1:346596979467:android:657b418c91ab33c5b6e80e',
    messagingSenderId: '346596979467',
    projectId: 'pseicrud',
    storageBucket: 'pseicrud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-gaC9a5D8pyTCrP6jIEohjzo3WWUPpw',
    appId: '1:346596979467:ios:6fa1d024a9885e1db6e80e',
    messagingSenderId: '346596979467',
    projectId: 'pseicrud',
    storageBucket: 'pseicrud.firebasestorage.app',
    iosBundleId: 'com.example.pseicrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX-gaC9a5D8pyTCrP6jIEohjzo3WWUPpw',
    appId: '1:346596979467:ios:6fa1d024a9885e1db6e80e',
    messagingSenderId: '346596979467',
    projectId: 'pseicrud',
    storageBucket: 'pseicrud.firebasestorage.app',
    iosBundleId: 'com.example.pseicrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHRpiex6ULSuDQuLsLgeTm7xozFvrPJOw',
    appId: '1:346596979467:web:fddbba6748369de8b6e80e',
    messagingSenderId: '346596979467',
    projectId: 'pseicrud',
    authDomain: 'pseicrud.firebaseapp.com',
    storageBucket: 'pseicrud.firebasestorage.app',
    measurementId: 'G-KXPJEZNX4T',
  );

}